#!/usr/bin/env python3
"""Generate and verify characterization/SUMMARY.md from committed sim/ evidence.

Offline and deterministic: reads the files named in characterization/sources.json
(never globs sim/), checks their sha256 pins, recomputes every min/max from the
CSV/JSON tables, and renders SUMMARY.md. It runs no simulation and emits no
pass/fail-versus-spec column (the repo has no ratified spec, #148).

  python3 characterization/gen_summary.py --update-hashes   # (re)pin sha256 in sources.json
  python3 characterization/gen_summary.py --write           # regenerate SUMMARY.md
  python3 characterization/gen_summary.py --check           # CI: hashes + freshness
"""
import argparse
import csv
import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
SOURCES = HERE / "sources.json"
SUMMARY = HERE / "SUMMARY.md"


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def load_sources(path=SOURCES):
    return json.loads(Path(path).read_text())


def source_files(ds):
    """(label, relative path, pinned sha or None) for every file a dataset cites."""
    out = [("record", ds["record"], ds.get("record_sha256"))]
    for i, p in enumerate(ds.get("extra_records", [])):
        out.append(("record", p, (ds.get("extra_records_sha256") or [None] * (i + 1))[i]))
    for t in ds["tables"]:
        out.append(("table", t["path"], t.get("sha256")))
    return out


def check_hashes(src, root=ROOT):
    """Return a list of problems: missing file, unpinned hash, or hash mismatch."""
    problems = []
    for ds in src["datasets"]:
        for label, rel, pinned in source_files(ds):
            p = Path(root) / rel
            if not p.is_file():
                problems.append(f"{ds['id']}: missing {label} file {rel}")
            elif not pinned:
                problems.append(f"{ds['id']}: no sha256 pinned for {rel}")
            elif sha256_file(p) != pinned:
                problems.append(f"{ds['id']}: sha256 changed for {rel}")
    return problems


def update_hashes(src, root=ROOT):
    for ds in src["datasets"]:
        ds["record_sha256"] = sha256_file(Path(root) / ds["record"])
        if ds.get("extra_records"):
            ds["extra_records_sha256"] = [sha256_file(Path(root) / p) for p in ds["extra_records"]]
        for t in ds["tables"]:
            t["sha256"] = sha256_file(Path(root) / t["path"])
    return src


def read_rows(table, root=ROOT):
    p = Path(root) / table["path"]
    if table.get("kind") == "json":
        obj = json.loads(p.read_text())
        for key in table["rows_path"].split("."):
            # A list step takes an integer index (e.g. klt reports: "corners.0.measurements").
            obj = obj[int(key)] if isinstance(obj, list) else obj[key]
        return [{k: ("" if v is None else str(v)) for k, v in r.items()} for r in obj]
    with open(p, newline="") as f:
        return list(csv.DictReader(f))


def to_float(s):
    try:
        v = float(s)
    except (TypeError, ValueError):
        return None
    return v if v == v else None


def extrema(rows, column, where=None):
    """min/max of a numeric column over rows matching `where`.

    Non-numeric cells (e.g. NA, empty) are counted, not silently dropped.
    """
    sel = [r for r in rows if all(r.get(k) == v for k, v in (where or {}).items())]
    vals = [to_float(r.get(column)) for r in sel]
    nums = [v for v in vals if v is not None]
    return {
        "rows": len(sel),
        "numeric": len(nums),
        "non_numeric": len(sel) - len(nums),
        "min": min(nums) if nums else None,
        "max": max(nums) if nums else None,
    }


def coverage(rows, columns, where=None):
    sel = [r for r in rows if all(r.get(k) == v for k, v in (where or {}).items())]
    out = {}
    for c in columns:
        seen = sorted({r.get(c, "") for r in sel}, key=lambda s: (to_float(s) is None, to_float(s) or 0, s))
        out[c] = seen
    return out


def fmt(v):
    return "n/a" if v is None else f"{v:.6g}"


def fmt_cov(cov):
    parts = []
    for c, vals in cov.items():
        if len(vals) > 8:
            parts.append(f"`{c}`: {len(vals)} distinct ({vals[0]} .. {vals[-1]})")
        else:
            parts.append(f"`{c}`: {', '.join(vals) if vals else '-'}")
    return "; ".join(parts)


def esc(s):
    return str(s).replace("|", "\\|")


def render(src, root=ROOT):
    L = []
    w = L.append
    w("# Characterization summary")
    w("")
    w("<!-- GENERATED by characterization/gen_summary.py from characterization/sources.json. Do not edit by hand. -->")
    w("")
    w("This file collects the numerical bounds that the committed `sim/` records support, with")
    w("the conditions under which each holds. Every min/max below is recomputed from the cited")
    w("CSV/JSON by `gen_summary.py`; CI fails if a source changed, a bound moved, or this file")
    w("is stale. It runs no simulation.")
    w("")
    w("It is a statement of measured evidence only. There is **no ratified spec** (see gaps),")
    w("so there is deliberately no pass/fail-versus-spec column, and no target is derived from")
    w("any measurement here. `non-numeric` counts cells such as `NA` that are excluded from")
    w("the min/max.")
    w("")
    w("## Open gaps")
    w("")
    w("| Gap | Tracker | Detail |")
    w("| --- | --- | --- |")
    for g in src["gaps"]:
        w(f"| {esc(g['title'])} | {g['issue']} | {esc(g['text'])} |")
    w("")
    gap_by_id = {g["id"]: g for g in src["gaps"]}
    for sec in src["sections"]:
        dss = [d for d in src["datasets"] if d["section"] == sec["id"]]
        if not dss:
            continue
        w(f"## {sec['title']}")
        w("")
        for ds in dss:
            tables = {t["id"]: t for t in ds["tables"]}
            cache = {tid: read_rows(t, root) for tid, t in tables.items()}
            w(f"### {ds['id']}")
            w("")
            w(f"- **PDK**: {ds['pdk']}")
            w(f"- **Status**: {ds['status']}")
            w(f"- **DUT revision**: {ds['dut_revision']}")
            w(f"- **Context**: {ds['context']}")
            w(f"- **Conditions**: {ds['conditions']}")
            w(f"- **Method**: {ds['method']}")
            w(f"- **Record**: `{ds['record']}` (sha256 `{ds['record_sha256']}`)")
            for p, h in zip(ds.get("extra_records", []), ds.get("extra_records_sha256", [])):
                w(f"- **Record**: `{p}` (sha256 `{h}`)")
            for t in ds["tables"]:
                w(f"- **Table `{t['id']}`**: `{t['path']}` (sha256 `{t['sha256']}`)")
            for n in ds.get("notes", []):
                w(f"- **Note**: {n}")
            if ds.get("gap_ids"):
                refs = ", ".join(f"{gap_by_id[g]['title']} ({gap_by_id[g]['issue']})" for g in ds["gap_ids"])
                w(f"- **Gaps**: {refs}")
            w("")
            w("| Quantity | Units | Table | Filter | Rows | Non-numeric | Min | Max | Corner coverage actually present |")
            w("| --- | --- | --- | --- | --- | --- | --- | --- | --- |")
            for me in ds["metrics"]:
                rows = cache[me["table"]]
                where = me.get("where")
                e = extrema(rows, me["column"], where)
                cov = coverage(rows, me.get("coverage_columns", []), where)
                filt = ", ".join(f"{k}={v}" for k, v in (where or {}).items()) or "-"
                w(f"| {esc(me['quantity'])} (`{me['column']}`) | {esc(me['units'])} | `{me['table']}` | {esc(filt)} "
                  f"| {e['rows']} | {e['non_numeric']} | {fmt(e['min'])} | {fmt(e['max'])} | {esc(fmt_cov(cov))} |")
            w("")
    return "\n".join(L).rstrip("\n") + "\n"


def check(src, root=ROOT, summary_path=SUMMARY):
    problems = check_hashes(src, root)
    if problems:
        return problems
    fresh = render(src, root)
    p = Path(summary_path)
    if not p.is_file():
        return [f"{p} is missing; run gen_summary.py --write"]
    if p.read_text() != fresh:
        return [f"{p} is stale against a fresh generation; run gen_summary.py --write and recommit"]
    return []


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--update-hashes", action="store_true")
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    src = load_sources()
    if a.update_hashes:
        SOURCES.write_text(json.dumps(update_hashes(src), indent=1) + "\n")
        print(f"pinned sha256 in {SOURCES.relative_to(ROOT)}")
        return 0
    if a.write:
        problems = check_hashes(src)
        if problems:
            print("\n".join(problems), file=sys.stderr)
            return 1
        SUMMARY.write_text(render(src))
        print(f"wrote {SUMMARY.relative_to(ROOT)}")
        return 0
    problems = check(src)
    if problems:
        print("characterization check FAILED:", file=sys.stderr)
        print("\n".join("  " + p for p in problems), file=sys.stderr)
        return 1
    print("characterization summary is fresh; all source hashes match.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
