#!/usr/bin/env python3
"""sg13g2-pll :: sim/sg13cmos5l-postlayout-pex-pvt/testbench/gen_pex_ladder.py
(issue #102, Part of #16 -- post-layout PEX arms for pfd and lock_detector)

Generates the POST-LAYOUT lock_detector recovery + phase-error-ladder decks
for the flat extracted DUT, mirroring the sibling campaign's
../../sg13cmos5l-lock-detector-window machinery:

  * the stimulus, .ic start states, settle window, measurement names and
    solver options are copied verbatim from that campaign's
    tb_lock_recovery.sp.tmpl / tb_lock_ladder_point.sp.tmpl +
    gen_ladder.py, so the per-corner reduction is reusable UNCHANGED --
    run_lock_detector.sh pipes these decks' concatenated stdout through
    the sibling campaign's own `gen_ladder.py reduce`, which cannot tell
    them apart from the schematic decks it was written for (every .meas
    scalar name is identical);
  * the ONLY structural differences are forced by the extraction itself:
    the DUT is one flat subckt, so each copy is instantiated via the
    make-inst.py line passed in --inst-* (pin order derived from the
    extracted cell's own .SUBCKT pin list), and the integrating node is a
    top-level node (the extracted cell exposes VWIN as a pin, wired by
    make-inst to a per-copy top node `<inst>_vwin`), so .ic and the
    `va{k}_*` measurements reference top-level nodes instead of hierarchical
    `xa{k}.vwin` ones;
  * the ladder fractions are imported from the sibling campaign's
    gen_ladder.py (LADDER_FRACS_SETS), never re-defined here, so `gen` and
    `reduce` cannot disagree on the ladder shape (the campaign's own
    --fracs-set-must-match rule).

Subcommands:
  recovery   one recovery + supply-current deck: the XR (zero-phase-error
            copy), XIL (in-window supply current) and XIU (out-of-window
            supply current) copies, writing trec/lr_*/vr_*/idd_lock/
            idd_unlock .meas scalars exactly as tb_lock_recovery.sp.tmpl
            does.
  point     ONE phase-error ladder point k (copy A discharged-start +
            copy B charged-start) with the campaign's global index
            numbering, so `reduce` over the concatenated per-point stdout
            matches the merged-deck format it was written for. tau_k =
            fracs[k] * twin_r, identical arithmetic.
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_CAMPAIGN_GEN = os.path.normpath(os.path.join(
    _HERE, "../../sg13cmos5l-lock-detector-window/testbench/gen_ladder.py"))


def _load_campaign_gen():
    spec = importlib.util.spec_from_file_location("campaign_gen_ladder",
                                                  _CAMPAIGN_GEN)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _fracs(args, campaign):
    try:
        return campaign.LADDER_FRACS_SETS[args.fracs_set]
    except KeyError:
        raise SystemExit(
            "gen_pex_ladder: unknown --fracs-set {!r}; known sets: {}"
            .format(args.fracs_set, ", ".join(sorted(campaign.LADDER_FRACS_SETS))))


def _include(path):
    return ".include %s" % os.path.abspath(path)


_HEAD = """* sg13g2-pll :: sim/sg13cmos5l-postlayout-pex-pvt (issue #102, Part of #16)
* GENERATED BY gen_pex_ladder.py -- do not edit by hand.
* Post-layout twin of the sibling campaign's {kind}: same .lib/.options/
* stimulus/.meas skeleton, DUT = the flat extraction instantiated via
* make-inst.py, integrating node = the per-copy top node <inst>_vwin.

.lib {pdk_root}/{pdk}/libs.tech/ngspice/models/cornerMOShv.lib {mos}
.lib {pdk_root}/{pdk}/libs.tech/ngspice/models/cornerRES.lib {res}
.option scale=1 temp={temp}
.global sub!

{dut}
"""

_TAIL = """
.param vsup={vsup}
.param tref={tref}
.param trst={trst}
.param ttr=100p
.param ttd='tref'

Vsub sub! 0 0
Vdd vdd 0 dc {vsup}
Vsubs vsubs 0 dc 0

{devices}

{ic}

.options reltol=1e-3 abstol=1e-10 vntol=1e-5 chgtol=1e-13 itl4=5000 gmin=1e-11
.tran {tstep} {tstop}

.control
{control}
.endc
.end
"""


def recovery(args, campaign):
    vsup = float(args.vsup)
    control = "\n".join([
        "save lkr xr_vwin vddl#branch vddu#branch",
        "run",
        "meas tran trec when v(xr_vwin)={vmid} rise=1".format(vmid=args.vmid),
        "meas tran lr_min min v(lkr) from={t0} to={t1}".format(
            t0=args.tsettle, t1=args.tstop),
        "meas tran lr_max max v(lkr) from={t0} to={t1}".format(
            t0=args.tsettle, t1=args.tstop),
        "meas tran lr_avg avg v(lkr) from={t0} to={t1}".format(
            t0=args.tsettle, t1=args.tstop),
        "meas tran vr_min min v(xr_vwin) from={t0} to={t1}".format(
            t0=args.tsettle, t1=args.tstop),
        "meas tran vr_max max v(xr_vwin) from={t0} to={t1}".format(
            t0=args.tsettle, t1=args.tstop),
        "meas tran idd_lock   avg i(vddl) from={t0} to={t1}".format(
            t0=args.tsettle, t1=args.tstop),
        "meas tran idd_unlock avg i(vddu) from={t0} to={t1}".format(
            t0=args.tsettle, t1=args.tstop),
    ])
    devices = "\n".join([
        "* ---- zero-phase-error stimulus (UP and DN identical: XOR sees nothing)",
        "Vup0 up0 0 pulse(0 {v} 'ttd' 'ttr' 'ttr' 'trst' 'tref')".format(v=vsup),
        "Vdn0 dn0 0 pulse(0 {v} 'ttd' 'ttr' 'ttr' 'trst' 'tref')".format(v=vsup),
        "",
        "* ---- recovery copy: starts fully discharged with no phase error",
        "* ---- per-block supply current, on their own ideal rails: XIL in-window",
        "*      (tau=0), XIU out-of-window (tau={taubig})".format(
            taubig=args.taubig),
        "Vddl vddl 0 dc {v}".format(v=vsup),
        "Vddu vddu 0 dc {v}".format(v=vsup),
        "Vupu upu 0 pulse(0 {v} 'ttd' 'ttr' 'ttr' '{taubig}+trst' 'tref')".format(
            v=vsup, taubig=args.taubig),
        "Vdnu dnu 0 pulse(0 {v} 'ttd+{taubig}' 'ttr' 'ttr' 'trst' 'tref')".format(
            v=vsup, taubig=args.taubig),
    ])
    ic = ".ic v(xr_vwin)=0 v(xil_vwin)={v} v(xiu_vwin)=0".format(v=vsup)
    insts = "\n".join(_include(p) for p in
                      (args.inst_r, args.inst_il, args.inst_iu))
    out = (_HEAD.format(kind="tb_lock_recovery.sp.tmpl", pdk_root=args.pdk_root,
                        pdk=args.pdk, mos=args.corner_mos,
                        res=args.corner_res, temp=args.temp,
                        dut=_include(args.dut))
           + insts
           + _TAIL.format(vsup=vsup, tref=args.tref, trst=args.trst,
                          tstep=args.tstep, tstop=args.tstop,
                          devices=devices, ic=ic, control=control))
    open(args.out, "w").write(out)
    return 0


def point(args, campaign):
    fracs = _fracs(args, campaign)
    if not (0 <= args.only_index < len(fracs)):
        raise SystemExit("gen_pex_ladder: --only-index %s out of range" %
                         args.only_index)
    k = args.only_index
    frac = fracs[k]
    tau = frac * float(args.twin)
    vsup = float(args.vsup)

    devices = [
        "* ladder point {k}: tau = {f:.2f} x twin_r = {tau:.6e} s".format(
            k=k, f=frac, tau=tau),
        "Vupl{k} upl{k} 0 pulse(0 {v} 'ttd' 'ttr' 'ttr' '{tau:.6e}+trst' "
        "'tref')".format(k=k, v=vsup, tau=tau),
        "Vdnl{k} dnl{k} 0 pulse(0 {v} 'ttd+{tau:.6e}' 'ttr' 'ttr' 'trst' "
        "'tref')".format(k=k, v=vsup, tau=tau),
    ]
    control = ["save lka{k} lkb{k} xa{k}_vwin xb{k}_vwin".format(k=k), "run"]
    for cp in ("a", "b"):
        for stat in ("min", "max", "avg"):
            control.append(
                "meas tran l{c}{k}_{s} {s} v(lk{c}{k}) from={t0} "
                "to={t1}".format(c=cp, k=k, s=stat, t0=args.tsettle,
                                 t1=args.tstop))
    for stat in ("min", "max", "avg"):
        control.append(
            "meas tran va{k}_{s} {s} v(xa{k}_vwin) from={t0} "
            "to={t1}".format(k=k, s=stat, t0=args.tsettle, t1=args.tstop))
    ic = ".ic v(xa{k}_vwin)=0 v(xb{k}_vwin)={v}".format(k=k, v=vsup)
    insts = "\n".join(_include(p) for p in (args.inst_a, args.inst_b))
    out = (_HEAD.format(kind="tb_lock_ladder_point.sp.tmpl",
                        pdk_root=args.pdk_root, pdk=args.pdk,
                        mos=args.corner_mos, res=args.corner_res,
                        temp=args.temp, dut=_include(args.dut))
           + insts
           + _TAIL.format(vsup=vsup, tref=args.tref, trst=args.trst,
                          tstep=args.tstep, tstop=args.tstop,
                          devices="\n".join(devices), ic=ic,
                          control="\n".join(control)))
    open(args.out, "w").write(out)
    return 0


def main() -> int:
    campaign = _load_campaign_gen()
    p = argparse.ArgumentParser()
    sub = p.add_subparsers(dest="cmd", required=True)

    def common(sp):
        sp.add_argument("--out", required=True)
        sp.add_argument("--dut", required=True)
        sp.add_argument("--corner-mos", required=True)
        sp.add_argument("--corner-res", required=True)
        sp.add_argument("--temp", required=True)
        sp.add_argument("--vsup", required=True)
        sp.add_argument("--vmid", required=True)
        sp.add_argument("--tref", required=True)
        sp.add_argument("--trst", required=True)
        sp.add_argument("--tstep", required=True)
        sp.add_argument("--tstop", required=True)
        sp.add_argument("--tsettle", required=True)
        sp.add_argument("--pdk-root", required=True)
        sp.add_argument("--pdk", required=True)

    r = sub.add_parser("recovery")
    common(r)
    r.add_argument("--taubig", required=True)
    r.add_argument("--inst-r", required=True)
    r.add_argument("--inst-il", required=True)
    r.add_argument("--inst-iu", required=True)
    r.set_defaults(fn=recovery)

    g = sub.add_parser("point")
    common(g)
    g.add_argument("--fracs-set", required=True)
    g.add_argument("--twin", required=True)
    g.add_argument("--only-index", type=int, required=True)
    g.add_argument("--inst-a", required=True)
    g.add_argument("--inst-b", required=True)
    g.set_defaults(fn=point)

    args = p.parse_args()
    return args.fn(args, campaign)


if __name__ == "__main__":
    raise SystemExit(main())
