#!/usr/bin/env python3
"""sg13g2-pll :: sim/sg13cmos5l-postlayout-pex-pvt/testbench/make-inst.py
(issue #30, Part of #16)

Emits the `X<inst> ... <cell>` instantiation line for an extracted cell by
reading that cell's own `.SUBCKT` pin list, instead of transcribing a port
order by hand.

This matters because `klt extract` exposes EVERY labelled net of a routed
cell as a pin -- `pll_vco` has 33, of which only 8 are the schematic's own
ports -- so a hand-written port order is a silent-miswire risk that would
look like a physical post-layout effect in the results.

Pins named on the command line as NAME=NODE are wired to NODE. Every other
pin is wired to a top-level node of the same name (the extracted internal net
simply surfaces at the top level, connected to nothing else), which is
electrically identical to leaving it internal.

Usage:
  make-inst.py <netlist.spice> <cell> <instname> [PIN=NODE ...] > inst.spice
"""

from __future__ import annotations

import re
import sys


def subckt_pins(path: str, cell: str) -> list[str]:
    text = open(path).read()
    lines = text.splitlines()
    joined: list[str] = []
    for ln in lines:
        if ln.startswith("+") and joined:
            joined[-1] += " " + ln[1:].strip()
        else:
            joined.append(ln)
    pat = re.compile(r"^\s*\.subckt\s+" + re.escape(cell) + r"\s+(.*)$", re.I)
    for ln in joined:
        m = pat.match(ln)
        if m:
            return m.group(1).split()
    sys.exit("FATAL: no .SUBCKT %s found in %s" % (cell, path))


def main() -> int:
    netlist, cell, inst = sys.argv[1], sys.argv[2], sys.argv[3]
    mapping = dict(a.split("=", 1) for a in sys.argv[4:])

    pins = subckt_pins(netlist, cell)
    unknown = sorted(set(mapping) - set(pins))
    if unknown:
        sys.exit(
            "FATAL: %s has no pin(s) %s -- refusing to emit a miswired "
            "instantiation (pins are: %s)" % (cell, ", ".join(unknown), " ".join(pins))
        )

    nodes = [mapping.get(p, p) for p in pins]
    print("* generated by make-inst.py from %s's own .SUBCKT pin list" % cell)
    print("* %d pins, %d explicitly wired: %s"
          % (len(pins), len(mapping),
             " ".join("%s->%s" % kv for kv in sorted(mapping.items()))))
    line = "X%s %s %s" % (inst, " ".join(nodes), cell)
    # SPICE continuation so no emitted line exceeds a comfortable width.
    words = line.split()
    out, cur = [], words[0]
    for w in words[1:]:
        if len(cur) + 1 + len(w) > 72:
            out.append(cur)
            cur = "+ " + w
        else:
            cur += " " + w
    out.append(cur)
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
